# PostgreSQL properties
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/spring_hibernate_db
db.username=postgres
db.password=12345678

# Hibernate properties
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
